
spring:
  profiles:
    active:
      - dev

---

spring:
  config:
    activate:
      on-profile: test
server:
  host: localhost
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod
server:
  host: localhost
  port: 8080

---

spring:
  config:
    activate:
      on-profile: dev
server:
  host: localhost
  port: 8080