
spring:
  profiles:
    active:
      - dev

---

spring:
  config:
    activate:
      on-profile: test
  security:
    user:
      name: pedro
      password: 123456

server:
  host: localhost
  port: 8081

---

spring:
  config:
    activate:
      on-profile: prod
server:
  host: localhost
  port: 8080

---

spring:
  config:
    activate:
      on-profile: dev
server:
  host: localhost
  port: 8080